# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='links.Profile')),
                ('avatar', models.ImageField(upload_to='')),
            ],
            bases=('links.profile',),
        ),
    ]
