# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170503_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='begins_date',
            field=models.DateField(null=True, verbose_name='starts'),
        ),
        migrations.AddField(
            model_name='event',
            name='ends_date',
            field=models.DateField(null=True, verbose_name='ends'),
        ),
        migrations.AlterField(
            model_name='event',
            name='begins_time',
            field=models.TimeField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(null=True, upload_to='', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_time',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='event name'),
        ),
    ]
