# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170503_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='address (street name & number)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='venue name'),
        ),
    ]
