# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170504_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends_time',
            field=models.TimeField(null=True, verbose_name=''),
        ),
    ]
