# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170504_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='display_ramaining_tickets',
            new_name='display_remaining_tickets',
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(null=True, upload_to='events/cover/', verbose_name='cover image'),
        ),
    ]
