# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170504_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(default='', max_length=150, verbose_name='event subtitle'),
        ),
    ]
