# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170515_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsalesorder',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_sales_order', to='events.PaymentCustomer'),
        ),
        migrations.AddField(
            model_name='ticketsalesorder',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_sells', to='events.Event'),
        ),
        migrations.AddField(
            model_name='ticketsalesorder',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticketsalesorder',
            name='ticket_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_type_sold', to='events.Ticket'),
        ),
        migrations.AddField(
            model_name='ticketsalesorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ticketsalesorder',
            name='transaction_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name='ticketsalesorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
