# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_auto_20170515_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events_shopping_cart', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('expiration', models.DateTimeField(default=events.models.generate_expiration_datetime)),
                ('cart', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_selected', to='events.ShoppingCart')),
                ('ticket_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.Ticket')),
            ],
        ),
    ]
