# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250, null=True),
        ),
    ]
