# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20170516_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketselection',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticketselection',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
