# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20170517_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketselection',
            name='expiration',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
