# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20170517_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='line1',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='line2',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='line3',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='City and State'),
        ),
    ]
