# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20170520_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('credit_card_number', models.CharField(default='**** **** **** ****', max_length=19)),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='events.PaymentCustomer')),
            ],
        ),
        migrations.AddField(
            model_name='ticketsales',
            name='payment_authorization',
            field=models.CharField(default='99999999', max_length=30),
        ),
        migrations.AddField(
            model_name='ticketsales',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='ticketsales',
            name='credit_card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_bought', to='events.PaymentCreditCard'),
        ),
    ]
