# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20170520_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='card_holder',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Card Holder'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='city',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='state',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='line3',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
