# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20170521_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
