# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_shoppingcart_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='card_holder',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Card Holder Name'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='line1',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Street Name and Number'),
        ),
    ]
