# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20170522_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsales',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
