# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_ticketsales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsales',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='ticketsales',
            name='order_no',
            field=models.CharField(default='9999999', max_length=10, null=True),
        ),
    ]
