# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20170530_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsales',
            options={'ordering': ['-datetime']},
        ),
    ]
