# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20170824_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['begins_date', 'begins_time'], 'permissions': (('edit_event', 'Edit Event'), ('create_event', 'Edit Event'))},
        ),
    ]
