# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0007_auto_20170802_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_datetime', models.DateTimeField()),
                ('ends_datetime', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='coaches.Client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='coaches.Coach')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='coaches.Session')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='coaches.Venue')),
            ],
        ),
    ]
