# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20170803_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='online_call',
            field=models.BooleanField(default=False),
        ),
    ]
