# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointments_custome_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='already_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='send_payment_link',
            field=models.BooleanField(default=False),
        ),
    ]
