# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0011_auto_20170818_1724'),
        ('booking', '0008_auto_20170814_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_datetime', models.DateTimeField(null=True)),
                ('ends_datetime', models.DateTimeField(null=True)),
                ('online_call', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_request', to='coaches.Client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_request', to='coaches.Coach')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_request', to='coaches.Session')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_request', to='coaches.Venue')),
            ],
        ),
    ]
