# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('booking', '0009_appointmentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('credit_card', models.CharField(max_length=16, null=True)),
                ('auth_number', models.CharField(max_length=16, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed_timestamp', models.DateTimeField()),
                ('service_object_pk', models.IntegerField(null=True)),
                ('service_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointments',
            options={'permissions': (('add_appointment_coach_side', 'Add Appointment Coach Side'), ('appointment_history', 'Appointment History'), ('view_clients', 'View Clients'), ('view_active_bundles', 'View Active Bundle'), ('view_coach_appointment', 'View Coach Appointment'))},
        ),
    ]
