# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20170824_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'permissions': (('add_appointment_coach_side', 'Add Appointment Coach Side'), ('confirm_appointment', 'Confirm Appointment'), ('appointment_history', 'Appointment History'), ('view_clients', 'View Clients'), ('view_active_bundles', 'View Active Bundle'), ('view_coach_appointment', 'View Coach Appointment'))},
        ),
    ]
