# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20170824_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='processed_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
