# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import philios.models


class Migration(migrations.Migration):

    dependencies = [
        ('philios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=philios.models.UploadedImage.generate_upload_path)),
            ],
        ),
    ]
