# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:51
from __future__ import unicode_literals

from django.db import migrations
import philios.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('philios', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=philios.models.generate_upload_path),
        ),
    ]
