# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philios', '0005_auto_20170313_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_type',
            field=models.CharField(choices=[('LI', 'Link'), ('IM', 'Image'), ('VI', 'Video')], default='LI', max_length=2),
        ),
    ]
