# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('category', models.CharField(default='', max_length=150)),
                ('number_sessions', models.BooleanField(default=False)),
                ('upfront_payment_required', models.BooleanField(default=False)),
                ('down_payment_allow', models.BooleanField(default=False)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expires', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(null=True, verbose_name='ends')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(default='', max_length=150)),
                ('office_phone', models.CharField(default='', max_length=10)),
                ('mobile_phone', models.CharField(default='', max_length=10)),
                ('job_title', models.CharField(default=None, max_length=150, null=True)),
                ('current_city', models.CharField(default='', max_length=150)),
                ('default_skype_id', models.CharField(default='', max_length=50)),
                ('is_instante_booking_allow', models.BooleanField(default=False)),
                ('ask_before_booking', models.BooleanField(default=False)),
                ('google_calendar_account_id', models.CharField(default='', max_length=50)),
                ('google_calendar_id', models.CharField(default='', max_length=50)),
                ('sunday_works', models.BooleanField(default=False)),
                ('monday_works', models.BooleanField(default=False)),
                ('tuesday_works', models.BooleanField(default=False)),
                ('wednesday_works', models.BooleanField(default=False)),
                ('thursday_works', models.BooleanField(default=False)),
                ('friday_works', models.BooleanField(default=False)),
                ('saturday_works', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('length_hours', models.IntegerField(default=0)),
                ('length_minutes', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('category', models.CharField(default='', max_length=150)),
                ('face_to_face', models.BooleanField(default=False)),
                ('all_venues', models.BooleanField(default=False)),
                ('one_on_one', models.BooleanField(default=False)),
                ('groups_allow', models.BooleanField(default=False)),
                ('person_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('address', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='allow_on_venues',
            field=models.ManyToManyField(to='coaches.Venue'),
        ),
        migrations.AddField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach'),
        ),
        migrations.AddField(
            model_name='availablehour',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.Coach'),
        ),
    ]
