# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 20:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_auto_20170721_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='google_calender_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
