# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_auto_20170724_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='clients',
            field=models.ManyToManyField(to='coaches.Client'),
        ),
    ]
