# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0008_auto_20170803_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
