# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0009_session_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='short_bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
