# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0011_auto_20170818_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='number_sessions',
            new_name='half_hour',
        ),
        migrations.AddField(
            model_name='bundle',
            name='half_hour_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundle',
            name='hour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle',
            name='hour_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundle',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundle',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundle',
            name='nover_expires',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle',
            name='open_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
