# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0012_auto_20170821_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='nover_expires',
            new_name='never_expires',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
