# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0013_auto_20170821_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_open_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='open_session',
            field=models.IntegerField(default=0),
        ),
    ]
