# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0015_auto_20170821_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='minutes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
