# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0018_auto_20170824_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'permissions': (('edit_bundle', 'Edit bundle'),)},
        ),
    ]
